### ISSUE TITLE
< Produt Page > Add "Buy Now" Button to Product Page

### ISSUE THREAD

**Issue by batterydied** [batterydied/Aquatica#123]
The product page currently lacks a "Buy Now" button, which limits users to adding items to their cart before purchasing. Adding a "Buy Now" button will allow users to proceed directly to the checkout process, improving the user experience for those who want to make quick purchases.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a 'Buy Now' button next to the 'Add to Cart' button in the ProductPage component. The new button has the same styling as the existing 'Add to Cart' button and triggers a handleBuyNow function when clicked.

You can review changes in this commit: https://github.com/mnmnk43434/batterydied-Aquatica-89/commit/8a3787a4112604da0cb43599bf1e51a5934f5d49.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by batterydied** [comment]
Pretty simple implementation, finished.
