### ISSUE TITLE
< Nav Menu > Update Navigation Menu to Use <i> from Font Awesome for Icons

### ISSUE THREAD

**Issue by batterydied** [batterydied/Aquatica#131]
We need to update the navigation menu to use Font Awesome icons for better visual representation and consistency across the site. Currently, the nav items either lack icons or use outdated methods. Replacing these with Font Awesome will improve the user interface and align with the rest of the design.

**Comment by HaiyiCai** [comment]
Hi Benson, thank you for checking on the nav-menu. Is there specific areas you want me to change icons?

- [x] Let me know where I should change/ add, and where else you have implemented Font Awesome icons to give me a sense of what you expect for consistency across the cite. 

Thank you!

**Comment by batterydied** [comment]
It was a very simple change in nav menu so I did it and made a PR instead.
