### ISSUE TITLE
< Produt Page > Integrate hover effect for image panel inside of product page

### ISSUE THREAD

**Issue by batterydied** [batterydied/Aquatica#36]
Implement a hover effect for the image panel on the product page. When users hover over a thumbnail image, the main product image should update to reflect the hovered thumbnail, and a border is applied to the selected thumbnail for better visual feedback. This enhances the user experience by providing a more interactive and intuitive interface for browsing product images.

**Comment by HaiyiCai** [comment]
Further development of #19 , #25, #26
