### ISSUE TITLE
CHECK `role.md` **top 3 commit** Format

### ISSUE THREAD

**Issue by HaiyiCai** [batterydied/Aquatica#5]
Please double check your **top 3 commit** coding format in `role.md`, especially the links. Thank you.

**Comment by HaiyiCai** [comment]
From _Piazza_:
There are no specific requirements for the commits in this milestone. You can get a link to the commit by visiting the commit on GitHub and copying the link from the browser's address bar. 
- If you wanna make a commit for something that you did that was not code related or documentation related,
- you can add some text to your **_report file_** describing the progress you made and _**make a commit**_ of that. 
- After you make a commit, then go to the commit on GitHub copy the link then add the link to your report and then make that commit.

**Comment by wnauda** [comment]
Make sure your format is exactly the same as the example format here! https://github.com/umass-cs-326/ms02-example/blob/main/team/m2/roles.md
