### ISSUE TITLE
Create ProductRoutes.js

### ISSUE THREAD

**Issue by wnauda** [batterydied/Aquatica#59]
Create API routes for product data management including:

1. GET /products/[productid] retrieve the product with the specified product id to display on product page.
2. GET /products/all retrieve all products in the database to display on marketplace page.
3. POST /products create a new product using details from seller product page.
4. PUT /products/[productid] update an existing product with the specified product id using details from seller product page.
5. DELETE /products/[productid] delete an existing product with the specified product id.

These routes will connect to ProductController.js and enforce authentication with middleware to interface with ProfileRoutes.js to allow users to create edit and delete their own products.

Point Value: 4
Feature Size: Medium

**Comment by 0xasritha** [comment]
As I am responsible for the ProductService, I will handle the POST and PUT calls

**Comment by batterydied** [comment]
I can do both GET calls and the DELETE call
