### ISSUE TITLE
< Marketplace > Integrate Marketplace Page with Backend

### ISSUE THREAD

**Issue by wnauda** [batterydied/Aquatica#61]
Connect the marketplace page (both seller and buyer views) with the backend apis to handle the following:

1. Fetching product data.
2. Navigating to product pages for specific products.
3. Navigating to profile pages for specific sellers. (buyer view)

This will integrate with ProductService to manage communication with the backend.

Point Value: 3
Feature Size: Medium

**Comment by wnauda** [comment]
Wait, I actually don't think I am handling creating new products, that is going to the seller product page made by Asritha. Disregard that bullet point.

**Comment by HaiyiCai** [comment]
> Wait, I actually don't think I am handling creating new products, that is going to the seller product page made by Asritha. Disregard that bullet point.

Winifred, you can always edit the comments.😆

**Comment by 0xasritha** [comment]
I created the GH issue for a seller product page here: https://github.com/batterydied/Aquatica/issues/64
