### ISSUE TITLE
< Auth System > Set Up Authentication Controller

### ISSUE THREAD

**Issue by HaiyiCai** [batterydied/Aquatica#67]
- **Description**: Implement the business logic for user authentication, including handling login, registration, and logout operations. This controller will interact with the _UserModel_ to validate credentials, hash passwords for secure storage, and manage tokens for user sessions. It will also handle errors related to invalid credentials, missing fields, or failed login attempts.
- **Tag**: `#67`
- **Owner**: Haiyi
- **Expected Outcome**: A controller that manages authentication logic, including verifying user credentials, generating tokens, and managing user sessions.

**Comment by HaiyiCai** [comment]
Includes logic for managing user authentication, including:

- [x]  **Registering users**: Handles user registration with validations for required fields and password security
  - Validates the input fields (e.g., email format, password length).
  - Hashes the password using bcrypt before storing it in the database.
  - Stores the new user's details in the database (using **_UserModel.js_**).
  - Generates a token or session to authorize the user for subsequent requests.

- [x] **Logging in users**: Verifies credentials, generates authentication tokens, and responds with user details.
  - Queries the _**UserModel.js**_ to find the user by email.
  - Compares the hashed password stored in the database with the one entered by the user.
  - If the credentials are valid, generates a JWT to authenticate the user for future requests.
  - Handles invalid login attempts with appropriate error messages.

- [x] **Logging out users**: Invalidates tokens to ensure users can securely log out.
  - Invalidates the user’s authentication token, effectively logging the user out.
  - **_Maybe_** involve token invalidation on multiple devices, if required.
  - On client-side logout, it may involve clearing tokens or session data.

- [x] **Resetting Password**: Allows users to reset their password securely.
  - The user provides the old password and the new password.
  - The _**AuthController.js**_ verifies the old password by checking it against the one stored in **_UserModel.js._**
  - If the old password is correct, the new password is hashed and saved in the database.

This controller will interface with _UserModel.js_ to manage authentication data in the database.

Point Value: 4
Feature Size: Medium

**Comment by wnauda** [comment]
How do you plan to implementing hashing for passwords? I found this tool called jsSHA, do you think something like that would be helpful? https://github.com/Caligatio/jsSHA

**Comment by HaiyiCai** [comment]
> How do you plan to implementing hashing for passwords? I found this tool called jsSHA, do you think something like that would be helpful? https://github.com/Caligatio/jsSHA

Thank you for the refrence, Winifred! I am taking a look and will get the hash implemented properly.
Ok so for the hashing we have a easier way to do using bcrypt! Still thank you for the comments~
