### ISSUE TITLE
< Nav-Menu >  Update Navigation Menu CSS

### ISSUE THREAD

**Issue by batterydied** [batterydied/Aquatica#78]
Description: Modify the CSS for the navigation menu to ensure it fits properly across all pages and adapts to different screen sizes for a responsive design. This includes:
Ensuring consistent alignment and spacing across desktop and mobile views.
Adding responsive behavior, such as collapsing the menu into a hamburger icon for smaller screens.
Testing compatibility with all existing pages to ensure no layout issues occur.

**Comment by HaiyiCai** [comment]
Thank you for the user experience and updating, Benson! I have copied the issue description to my Update issue #71. If it's possible, please link your PR to that one as well to show a complete work tree. Thanks again!

**Comment by batterydied** [comment]
I made the nav bar responsive, any additional CSS I'm leaving it to Haiyi
