### ISSUE TITLE
Set Up Nodemon as an NPM Command

### ISSUE THREAD

**Issue by batterydied** [batterydied/Aquatica#89]
Configure nodemon to run the server as a custom NPM script (npm run start) for easier development and quicker startup. This will streamline the development process by allowing the server to automatically restart whenever code changes are detected.

**Comment by batterydied** [comment]
Successfully added in the script for npm run start to run nodemon ./backend/server.js

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the 'scripts' section in package.json to include a 'start' script using nodemon for development. This allows the server to automatically restart when code changes are detected, streamlining the development process.

You can review changes in this commit: https://github.com/mnmnk43434/batterydied-Aquatica-89/commit/542975aa3cd8cb44483cdab2ded1c238b0ed61df.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
